export const locationSuggestions = [
  {
    'country': 'Bulgaria',
    'lng': 23.7,
    'searchType': 'G',
    'alternative': ['BG'],
    'index': 1,
    'bookingId': 'city-355866',
    'placeType': 'C',
    'placeKey': '100948',
    'countryIso': 'bg',
    'locationId': '-1',
    'name': 'Kʼoseva',
    'ufi': -835331,
    'isPopular': false,
    'region': 'Sofia',
    'lang': 'en',
    'lat': 42.4,
  },
  {
    'country': 'Bulgaria',
    'lng': 25.15,
    'searchType': 'G',
    'alternative': ['BG'],
    'index': 2,
    'bookingId': 'city-355411',
    'placeType': 'C',
    'placeKey': '100946',
    'countryIso': 'bg',
    'locationId': '-1',
    'name': 'Kʼochevtsi',
    'ufi': -835200,
    'isPopular': false,
    'region': 'Kardzhali',
    'lang': 'en',
    'lat': 41.6833,
  },
  {
    'country': 'Bulgaria',
    'lng': 25.3,
    'searchType': 'G',
    'alternative': ['BG'],
    'index': 3,
    'bookingId': 'city-355867',
    'placeType': 'C',
    'placeKey': '100949',
    'countryIso': 'bg',
    'locationId': '-1',
    'name': 'Kʼosevo',
    'ufi': -835333,
    'isPopular': false,
    'region': 'Kardzhali',
    'lang': 'en',
    'lat': 41.6167,
  },
  {
    'country': 'Bulgaria',
    'lng': 26.25,
    'searchType': 'G',
    'alternative': ['BG'],
    'index': 4,
    'bookingId': 'city-355869',
    'placeType': 'C',
    'placeKey': '100950',
    'countryIso': 'bg',
    'locationId': '-1',
    'name': 'Kʼosevtsi',
    'ufi': -835335,
    'isPopular': false,
    'region': 'Targovishte',
    'lang': 'en',
    'lat': 43.1,
  },
  {
    'country': 'Bulgaria',
    'lng': 26.6833,
    'searchType': 'G',
    'alternative': ['BG'],
    'index': 5,
    'bookingId': 'city-355624',
    'placeType': 'C',
    'placeKey': '100947',
    'countryIso': 'bg',
    'locationId': '-1',
    'name': 'Kʼolmen',
    'ufi': -835239,
    'isPopular': false,
    'region': 'Shumen',
    'lang': 'en',
    'lat': 43.0333,
  },
  {
    'country': 'Georgia',
    'lng': 41.4436,
    'searchType': 'G',
    'alternative': ['GE'],
    'index': 6,
    'bookingId': 'city-876445',
    'placeType': 'C',
    'placeKey': '449544',
    'countryIso': 'ge',
    'locationId': '-1',
    'name': 'Kʼochʼara',
    'ufi': -2328015,
    'isPopular': false,
    'lang': 'en',
    'lat': 42.8575,
  },
];
